version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3103:3306"
    expose:
      - 3103
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: typeorm
    volumes:
      - mysql-data:/var/lib/mysql
      - dbsocket:/var/run/mysqld
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      DATABASE_SOCKET: /var/run/mysqld/mysqld.sock
      PORT: 5000
    volumes:
      - .:/app
      - dbsocket:/var/run/mysqld

volumes:
  mysql-data:
  dbsocket:
