version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3103:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: typeorm
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
